package co.edu.uniquindio.compiladores.lexico


enum class Categoria
{
    ENTERO, CADENA_CARACTERES, CARACTER, DECIMAL, CENTI, IDENTIFICADOR, ESCAPE, OPERADOR_ADITIVO, OPERADOR_MULTIPLICATIVO, OPERADOR_ARITMETICO,
    OPERADOR_DE_ASIGNACION, OPERADOR_RELACIONAL, OPERADOR_LOGICO, PALABRA_RESERVADA, SEPARADOR_DE_SENTENCIA,
    SEPARADOR, NO_RECONOCIDO, ENTERO_CORTO, ENTERO_LARGO, DECIMAL_CORTO, DECIMAL_LARGO, ERROR, COMENTARIO_LINEA, COMENRARIO_BLOQUE
    ,SALTO_LINEA, LLAVE_ABRIR, LLAVE_CERRAR, CORCHETE_ABRIR, CORCHETE_CERRAR, PARENTESIS_ABRIR, PARENTESIS_CERRAR,
    OPERADOR_INICIAL, OPERADOR_TERMINAL, FIN_SENTENCIA, OPERADOR_DECREMENTO, OPERADOR_INCREMENTO, DOS_PUNTOS, NO_RETORNO
    , CONCATENADOR, NEGACION

}