package co.edu.uniquindio.compiladores.lexico

// CATEGORIA
// Clase de la categoria, es un enum
// su fucnion es que cuado sea llamado este reporte cual es la categoria correspondiente
// del lexema lanzado en el codigo de fuente
enum class Categoria {
	ENTERO, DECIMAL, IDENTIFICADOR, OPERADOR_ARITMETICO, OPERADOR_LOGICO, PARENTESIS_DERECHO,
	PARENTESIS_IZQUIERDO, OPERADOR_RELACIONAL, TIPO_DE_DATO, PALABRA_RESERVADA, OPERADOR_ASIGNACION,
	LLAVE_DERECHO, LLAVE_IZQUIERDO, CORCHETE_IZQUIERDO, CORCHETE_DERECHO, NO_RECONOCIDO,
	MAYUSCULA, MINUSCULA, TERMINAL, SEPARADOR, CARACTER_ESPECIAL, CARACTER, IDENTIFICADOR_DE_CLASE,
	PUNTO, FIN_DE_SENTENCIA, DOS_PUNTOS, COMENTARIO_DE_BLOQUE, COMENTARIO_DE_LINEA,
	CADENA_DE_CARACTER, OPERADOR_INCREMENTO, OPERADOR_DECREMENTO, IDENTIFICADOR_DE_METODO,
	IDENTIFICADOR_DE_CONSTANTES, OPERADOR_NEGACION, FIN_DE_CODIGO
}//FIN DE LA CLASE