package co.edu.uniquindio.compiladores.lexico


enum class Categoria{
    ENTERO, CADENA, CARACTER, DECIMAL, BOOLEANO, IDENTIFICADOR, ESCAPE, OPERADOR_ADITIVO, OPERADOR_ARITMETICO,
    OPERADOR_DE_ASIGNACION, OPERADOR_RELACIONAL, OPERADOR_LOGICO, PALABRA_RESERVADA, SEPARADOR_DE_SENTENCIA,
    SEPARADOR, NO_RECONOCIDO

}